/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dsid.ep;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.UIManager;
import java.awt.Dimension;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Server: Vai ser utilizada para inicializar a interface grafica do cliente
 */

public class Client {
    public static void main(String[] args) {

        UIManager.put("swing.boldMetal", Boolean.FALSE);

        javax.swing.SwingUtilities.invokeLater(() -> {
            ClientGui gui = new ClientGui("Client Manager");
        });
    }
}

/**
 * ClientGui: Aqui onde a interface gráfica vai ser criada
 *
 * @attr gui: A interface grafica principal
 * @attr CONNPANEL: String da tab onde o usuario pode conectar com o repositorio
 * @attr INFOPANEL: String da tab onde o usuario pode pesquisar pecas no repositorio
 * @attr SHOWPANEL: String da tab onde o usuario pode ver informacoes sobre uma determinada peca e seus subcomponentes
 * @attr MIN_WIDTH: A largura minima para que o programa funcione
 * @attr MIN_HEIGHT: A algura minima para que o programa funcione
 */
class ClientGui {

    private final JFrame gui;
    final static String CONNPANEL = "Server";
    final static String SHOWPANEL = "Search";
    final static String INFOPANEL = "Information";
    private String repository;
    private final int MIN_WIDTH = 600;
    private final int MIN_HEIGHT = 400;

    ClientGui(String name) {
        this.gui = new JFrame(name);
        setupFrame();
        setupPanel();
        this.gui.setVisible(true);
    }

    /**
     * setupFrame: Vai inicializar algumas propriedades do JFrame
     */
    private void setupFrame() {
        System.err.println("Setup Frame...");
        this.gui.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.gui.setMinimumSize(new Dimension(MIN_WIDTH, MIN_HEIGHT));
    }

    /**
     * setupFrame: Vai inicializar a interface grafica do cliente, ela vai ser baseada em tabs
     *
     * @see Panel
     */
    private void setupPanel() {
        System.err.println("Setup tabs...");
        JTabbedPane panel = new JTabbedPane();

        /**
         * O evendo do botao quit vai sair do programa
         */
        JButton quit = new JButton("quit");
        quit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });

        JPanel connPanel = new JPanel(new BorderLayout());
        connPanel.add(new ConnectPanel(), BorderLayout.CENTER);
        connPanel.add(quit, BorderLayout.PAGE_END);
        connPanel.setBorder(BorderFactory.createEmptyBorder(10,10,10,10));
        panel.addTab(CONNPANEL, connPanel);

        JPanel showPanel = new JPanel(new BorderLayout());
        showPanel.add(new ShowPanel(), BorderLayout.CENTER);
        panel.addTab(SHOWPANEL, showPanel);

        JPanel infoPanel = new JPanel(new BorderLayout());
        infoPanel.add(new InfoPanel(), BorderLayout.CENTER);
        panel.addTab(INFOPANEL, infoPanel);

        gui.getContentPane().add(panel, BorderLayout.CENTER);
    }

}
